name: API Blueprint

on:
  push:
    paths: 
      - '*.apib'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build API Blueprint in aglio container
      run: |
        docker run \
        -v ${{ github.workspace }}:/apiblueprint \
        -t hgoblin/aglio:latest \
        -i /apiblueprint/api.apib -o /apiblueprint/index.html
        cat ${{ github.workspace }}/index.html
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        cd ${{ github.workspace }}
        git commit -m "Add changes" -a
        git push
Inputs
